apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-sql-client-config-20
  namespace: flink
data:
  # 이 파일은 SQL Gateway Pod에 마운트됩니다.
  config.yaml: |+

    rest.address: flink-cluster-20-rest.flink.svc.cluster.local
    rest.port: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-sql-client
  namespace: flink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-sql-client
  template:
    metadata:
      labels:
        app: flink-sql-client
    spec:
      containers:
      - name: flink-sql-client
        env:
          - name: TZ
            value: Asia/Seoul
        image: flink:2.0.1-java17
        command: ["sleep", "infinity"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
            - name: sql-client-config
              mountPath: /opt/flink/conf/config.yaml
              subPath: config.yaml
      volumes:
        - name: sql-client-config
          configMap:
            name: flink-sql-client-config-20